wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    code_path: code/ppo.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1636516295
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 13
      - 16
      4: 3.9.5
      5: 0.12.6
      8:
      - 5
anneal_lr:
  desc: null
  value: true
batch_size:
  desc: null
  value: 512
capture_video:
  desc: null
  value: true
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: true
cuda:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.01
exp_name:
  desc: null
  value: ppo
gae:
  desc: null
  value: true
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
gym_id:
  desc: null
  value: CartPole-v1
learning_rate:
  desc: null
  value: 0.00025
max_grad_norm:
  desc: null
  value: 0.5
minibatch_size:
  desc: null
  value: 128
norm_adv:
  desc: null
  value: true
num_envs:
  desc: null
  value: 4
num_minibatches:
  desc: null
  value: 4
num_steps:
  desc: null
  value: 128
seed:
  desc: null
  value: 1
target_kl:
  desc: null
  value: null
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 25000
track:
  desc: null
  value: true
update_epochs:
  desc: null
  value: 4
vf_coef:
  desc: null
  value: 0.5
wandb_entity:
  desc: null
  value: null
wandb_project_name:
  desc: null
  value: cleanRL
